import type {
  FormSchema,
  FormTheme,
  GeneratedFormDraft,
  OcrTemplate,
  WebhookProvider,
} from "@/types/form";

export type TemplateSource = "public_benchmark" | "user_research" | "internal_demo";

export interface SceneTemplate {
  id: string;
  name: string;
  source: TemplateSource;
  category: string;
  scenario: string;
  description: string;
  theme: FormTheme;
  formSchema: FormSchema;
  suggestedPrompts: string[];
  agentQuickActions: string[];
  ocrTemplate?: OcrTemplate;
  webhookPreset?: WebhookProvider;
  successCopy?: string;
}

export const sceneTemplates: SceneTemplate[] = [
  {
    id: "lead-capture",
    name: "线索收集表",
    source: "public_benchmark",
    category: "增长获客",
    scenario: "官网、落地页、活动页潜客收集",
    description: "适合快速收集潜在客户需求、联系方式和预算计划。",
    theme: "business",
    webhookPreset: "generic",
    suggestedPrompts: [
      "把这个线索收集表改成适合 SaaS 官网获客。",
      "增加预算范围选项，并让字段更适合销售跟进。",
    ],
    agentQuickActions: [
      "改成适合 SaaS 官网获客",
      "增加预算范围选项",
      "检查字段是否太多",
      "生成销售跟进提示",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "contact_name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入你的姓名或称呼",
        },
        {
          key: "contact_method",
          label: "我们可以通过什么方式联系你？",
          type: "text",
          required: true,
          placeholder: "手机号、邮箱或微信都可以",
        },
        {
          key: "interest_area",
          label: "你对哪类产品或服务感兴趣？",
          type: "select",
          required: true,
          options: [
            { label: "产品咨询", value: "product_consulting" },
            { label: "价格方案", value: "pricing" },
            { label: "合作洽谈", value: "partnership" },
            { label: "其他需求", value: "other" },
          ],
        },
        {
          key: "budget_timeline",
          label: "你的预算或计划时间大概是？",
          type: "radio",
          required: false,
          options: [
            { label: "本月内", value: "this_month" },
            { label: "1-3 个月", value: "one_to_three_months" },
            { label: "还在了解", value: "researching" },
          ],
        },
        {
          key: "extra_notes",
          label: "还有什么想补充的吗？",
          type: "textarea",
          required: false,
          placeholder: "简单说说你的业务背景或具体需求",
        },
      ],
    },
  },
  {
    id: "contact-us",
    name: "联系我们表",
    source: "public_benchmark",
    category: "官网咨询",
    scenario: "网站、个人主页、机构页面接收咨询",
    description: "适合收集咨询内容，并推送给客服或团队负责人。",
    theme: "minimal",
    webhookPreset: "feishu_bot",
    suggestedPrompts: [
      "改成适合企业官网的联系我们表。",
      "增加服务类型选项，并生成自动回复文案。",
    ],
    agentQuickActions: [
      "改成适合个人咨询",
      "改成适合企业官网",
      "增加服务类型选项",
      "生成自动回复文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入你的姓名",
        },
        {
          key: "email_or_phone",
          label: "你的邮箱或电话是？",
          type: "text",
          required: true,
          placeholder: "方便我们回复你",
        },
        {
          key: "topic",
          label: "你想咨询什么？",
          type: "textarea",
          required: true,
          placeholder: "请简单描述你的问题或需求",
        },
        {
          key: "preferred_contact_time",
          label: "希望我们什么时候联系你？",
          type: "text",
          required: false,
          placeholder: "例如：工作日下午、明天上午",
        },
      ],
    },
  },
  {
    id: "event-registration",
    name: "活动报名表",
    source: "public_benchmark",
    category: "活动运营",
    scenario: "会议、沙龙、直播、线下活动报名",
    description: "适合活动报名收集、席位安排和运营群通知。",
    theme: "business",
    webhookPreset: "feishu_bot",
    suggestedPrompts: [
      "改成高端沙龙报名，并加一个饮食偏好字段。",
      "加一个同行人数，并生成报名成功提示文案。",
    ],
    agentQuickActions: [
      "改成高端沙龙报名",
      "加一个饮食偏好字段",
      "加一个同行人数",
      "生成报名成功提示文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "attendee_name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入参会人姓名",
        },
        {
          key: "contact",
          label: "你的手机号或邮箱是？",
          type: "text",
          required: true,
          placeholder: "用于发送活动确认信息",
        },
        {
          key: "company",
          label: "你所在公司或组织是？",
          type: "text",
          required: false,
          placeholder: "例如：AI AgentFactory",
        },
        {
          key: "role",
          label: "你的职位或身份是？",
          type: "text",
          required: false,
          placeholder: "例如：产品负责人、开发者、设计师",
        },
        {
          key: "preference",
          label: "是否有饮食或座位偏好？",
          type: "textarea",
          required: false,
          placeholder: "如无特殊偏好可跳过",
        },
      ],
    },
  },
  {
    id: "event-feedback",
    name: "活动反馈表",
    source: "public_benchmark",
    category: "活动复盘",
    scenario: "活动结束后收集体验反馈和改进建议",
    description: "适合活动复盘、满意度分析和后续运营改进。",
    theme: "minimal",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合线上直播反馈。",
      "增加 NPS 评分，并精简成 3 个问题。",
    ],
    agentQuickActions: [
      "改成适合线上直播反馈",
      "增加 NPS 评分",
      "精简成 3 个问题",
      "生成反馈总结维度",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "event_name",
          label: "你参加的是哪场活动？",
          type: "text",
          required: true,
          placeholder: "请输入活动名称",
        },
        {
          key: "overall_rating",
          label: "你对本次活动整体满意吗？",
          type: "radio",
          required: true,
          options: [
            { label: "非常满意", value: "very_satisfied" },
            { label: "满意", value: "satisfied" },
            { label: "一般", value: "neutral" },
            { label: "不太满意", value: "unsatisfied" },
          ],
        },
        {
          key: "most_valuable_part",
          label: "哪个环节最有价值？",
          type: "textarea",
          required: false,
          placeholder: "例如：主题分享、圆桌讨论、互动问答",
        },
        {
          key: "improvement_suggestion",
          label: "哪些地方需要改进？",
          type: "textarea",
          required: false,
          placeholder: "欢迎写下具体建议",
        },
        {
          key: "join_next_event",
          label: "是否愿意参加后续活动？",
          type: "radio",
          required: false,
          options: [
            { label: "愿意", value: "yes" },
            { label: "看主题再决定", value: "depends" },
            { label: "暂不考虑", value: "no" },
          ],
        },
      ],
    },
  },
  {
    id: "satisfaction-survey",
    name: "客户满意度调查",
    source: "public_benchmark",
    category: "客户体验",
    scenario: "产品、服务、门店或交付后的满意度调查",
    description: "适合收集客户体验、改进意见和回访意愿。",
    theme: "business",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合门店服务满意度调查。",
      "改成适合软件产品反馈，并增加 NPS 评分。",
    ],
    agentQuickActions: [
      "改成适合门店服务",
      "改成适合软件产品反馈",
      "增加 NPS 评分",
      "检查问题是否引导性太强",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "product_or_service",
          label: "你使用的是哪项产品或服务？",
          type: "text",
          required: true,
          placeholder: "请输入产品、服务或门店名称",
        },
        {
          key: "satisfaction",
          label: "你的整体满意度如何？",
          type: "radio",
          required: true,
          options: [
            { label: "非常满意", value: "very_satisfied" },
            { label: "满意", value: "satisfied" },
            { label: "一般", value: "neutral" },
            { label: "不满意", value: "unsatisfied" },
          ],
        },
        {
          key: "best_part",
          label: "哪一项体验最好？",
          type: "textarea",
          required: false,
          placeholder: "告诉我们最值得保留的体验",
        },
        {
          key: "improvement_area",
          label: "哪一项最需要改进？",
          type: "textarea",
          required: false,
          placeholder: "请写下你最希望改进的地方",
        },
        {
          key: "allow_follow_up",
          label: "是否愿意被进一步回访？",
          type: "radio",
          required: false,
          options: [
            { label: "可以回访", value: "yes" },
            { label: "暂不需要", value: "no" },
          ],
        },
      ],
    },
  },
  {
    id: "product-recommendation",
    name: "产品推荐问卷",
    source: "public_benchmark",
    category: "互动转化",
    scenario: "根据用户偏好推荐产品、方案或服务",
    description: "适合做互动问卷、方案推荐和销售线索分层。",
    theme: "dark",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合课程推荐的互动问卷。",
      "改成适合软件方案推荐，并增加预算区间。",
    ],
    agentQuickActions: [
      "改成适合课程推荐",
      "改成适合软件方案推荐",
      "增加预算区间",
      "优化成更像互动测验",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "main_goal",
          label: "你主要想解决什么问题？",
          type: "textarea",
          required: true,
          placeholder: "简单描述你当前最想解决的需求",
        },
        {
          key: "usage_context",
          label: "你的使用场景是什么？",
          type: "select",
          required: true,
          options: [
            { label: "个人使用", value: "personal" },
            { label: "小团队协作", value: "small_team" },
            { label: "企业内部", value: "enterprise" },
            { label: "对外服务客户", value: "customer_facing" },
          ],
        },
        {
          key: "priority",
          label: "你更看重哪些因素？",
          type: "checkbox",
          required: true,
          options: [
            { label: "价格", value: "price" },
            { label: "易用性", value: "ease_of_use" },
            { label: "专业能力", value: "capability" },
            { label: "交付速度", value: "speed" },
          ],
        },
        {
          key: "budget",
          label: "你的预算范围大概是？",
          type: "radio",
          required: false,
          options: [
            { label: "先免费试用", value: "trial" },
            { label: "低预算", value: "low" },
            { label: "中等预算", value: "medium" },
            { label: "预算充足", value: "high" },
          ],
        },
        {
          key: "need_consultant",
          label: "是否需要人工顾问联系？",
          type: "radio",
          required: false,
          options: [
            { label: "需要", value: "yes" },
            { label: "暂不需要", value: "no" },
          ],
        },
      ],
    },
  },
  {
    id: "booking-consultation",
    name: "预约咨询表",
    source: "public_benchmark",
    category: "预约服务",
    scenario: "课程、服务、顾问、美容、线下门店预约",
    description: "适合预约服务、咨询排期和门店运营通知。",
    theme: "minimal",
    webhookPreset: "feishu_bot",
    suggestedPrompts: [
      "改成适合课程顾问预约。",
      "增加可选时间段，并生成预约确认文案。",
    ],
    agentQuickActions: [
      "改成适合课程顾问预约",
      "改成适合门店服务预约",
      "增加可选时间段",
      "生成预约确认文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "customer_name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入你的姓名",
        },
        {
          key: "service_type",
          label: "你想预约哪项服务？",
          type: "select",
          required: true,
          options: [
            { label: "初次咨询", value: "first_consultation" },
            { label: "方案沟通", value: "solution_discussion" },
            { label: "体验预约", value: "trial_booking" },
            { label: "其他服务", value: "other" },
          ],
        },
        {
          key: "preferred_time",
          label: "希望预约的日期和时间？",
          type: "text",
          required: true,
          placeholder: "例如：周三下午 3 点",
        },
        {
          key: "contact",
          label: "你的联系方式是？",
          type: "text",
          required: true,
          placeholder: "手机号、邮箱或微信",
        },
        {
          key: "special_notes",
          label: "是否有特殊说明？",
          type: "textarea",
          required: false,
          placeholder: "如有特殊偏好或限制，请提前告诉我们",
        },
      ],
    },
  },
  {
    id: "job-application",
    name: "招聘申请表",
    source: "public_benchmark",
    category: "招聘申请",
    scenario: "收集候选人信息和简历附件",
    description: "适合职位申请、简历收集和 HR 群通知。",
    theme: "business",
    ocrTemplate: "general_image",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合实习生招聘。",
      "加一个作品集链接，并检查候选人信息是否足够筛选。",
    ],
    agentQuickActions: [
      "改成适合实习生招聘",
      "加一个作品集链接",
      "增加简历上传字段",
      "检查候选人信息是否足够筛选",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "candidate_name",
          label: "你的姓名是？",
          type: "text",
          required: true,
          placeholder: "请输入真实姓名",
        },
        {
          key: "contact",
          label: "你的联系方式是？",
          type: "text",
          required: true,
          placeholder: "手机号或邮箱",
        },
        {
          key: "target_role",
          label: "你想申请哪个岗位？",
          type: "text",
          required: true,
          placeholder: "请输入岗位名称",
        },
        {
          key: "work_years",
          label: "你的工作年限是？",
          type: "select",
          required: true,
          options: [
            { label: "应届 / 实习", value: "intern_or_graduate" },
            { label: "1-3 年", value: "one_to_three" },
            { label: "3-5 年", value: "three_to_five" },
            { label: "5 年以上", value: "over_five" },
          ],
        },
        {
          key: "resume_file",
          label: "请上传简历。",
          type: "pdf",
          required: true,
          help_text: "建议上传 PDF 格式简历。",
        },
        {
          key: "portfolio_or_notes",
          label: "有什么补充说明？",
          type: "textarea",
          required: false,
          placeholder: "可以填写作品集链接、个人亮点或补充说明",
        },
      ],
    },
  },
  {
    id: "waitlist",
    name: "早鸟名单表",
    source: "public_benchmark",
    category: "增长获客",
    scenario: "新产品、内测、预发布页面收集早期用户",
    description: "适合收集早期用户意向、使用场景和内测邀请偏好。",
    theme: "dark",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合 AI 产品内测名单。",
      "增加用户角色字段，并生成早鸟邀请文案。",
    ],
    agentQuickActions: [
      "改成 AI 产品内测",
      "增加用户角色字段",
      "减少填写阻力",
      "生成早鸟邀请文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "contact_name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入你的姓名或昵称",
        },
        {
          key: "email",
          label: "你的邮箱是？",
          type: "email",
          required: true,
          placeholder: "用于发送内测邀请",
        },
        {
          key: "user_type",
          label: "你更接近哪类用户？",
          type: "select",
          required: true,
          options: [
            { label: "创业者", value: "founder" },
            { label: "产品 / 运营", value: "product_ops" },
            { label: "开发者", value: "developer" },
            { label: "企业团队", value: "enterprise_team" },
            { label: "其他", value: "other" },
          ],
        },
        {
          key: "pain_point",
          label: "你最希望它帮你解决什么问题？",
          type: "textarea",
          required: true,
          placeholder: "简单说说你的目标或当前痛点",
        },
        {
          key: "invite_preference",
          label: "是否愿意收到早鸟福利和产品更新？",
          type: "radio",
          required: false,
          options: [
            { label: "愿意", value: "yes" },
            { label: "只接收内测通知", value: "beta_only" },
          ],
        },
      ],
    },
  },
  {
    id: "newsletter-signup",
    name: "Newsletter 订阅表",
    source: "public_benchmark",
    category: "内容订阅",
    scenario: "内容站、个人品牌、产品更新订阅",
    description: "适合收集邮件订阅、内容兴趣和推送频率偏好。",
    theme: "retro",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合 AI 行业周报订阅。",
      "增加内容兴趣选项，并精简成更轻量的订阅表。",
    ],
    agentQuickActions: [
      "改成 AI 周报订阅",
      "增加内容兴趣",
      "压缩成 3 个问题",
      "生成订阅成功文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "email",
          label: "你的邮箱是？",
          type: "email",
          required: true,
          placeholder: "请输入常用邮箱",
        },
        {
          key: "name",
          label: "怎么称呼你？",
          type: "text",
          required: false,
          placeholder: "可选",
        },
        {
          key: "interests",
          label: "你对哪些内容更感兴趣？",
          type: "checkbox",
          required: true,
          options: [
            { label: "产品更新", value: "product_updates" },
            { label: "增长案例", value: "growth_cases" },
            { label: "AI 工具", value: "ai_tools" },
            { label: "行业观察", value: "industry_insights" },
          ],
        },
        {
          key: "frequency",
          label: "希望多久收到一次？",
          type: "radio",
          required: false,
          options: [
            { label: "每周", value: "weekly" },
            { label: "每月", value: "monthly" },
            { label: "有重要更新时", value: "major_updates" },
          ],
        },
      ],
    },
  },
  {
    id: "course-registration",
    name: "课程报名表",
    source: "public_benchmark",
    category: "教育培训",
    scenario: "公开课、训练营、工作坊和私教课程报名",
    description: "适合课程报名、学习目标收集和开课通知。",
    theme: "business",
    webhookPreset: "feishu_bot",
    suggestedPrompts: [
      "改成适合线上 AI 训练营报名。",
      "增加学习基础选项，并生成报名确认文案。",
    ],
    agentQuickActions: [
      "改成 AI 训练营报名",
      "增加学习基础选项",
      "增加上课时间偏好",
      "生成报名确认文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "student_name",
          label: "你的姓名是？",
          type: "text",
          required: true,
          placeholder: "请输入报名人姓名",
        },
        {
          key: "contact",
          label: "你的联系方式是？",
          type: "text",
          required: true,
          placeholder: "手机号、邮箱或微信",
        },
        {
          key: "course_name",
          label: "想报名哪类课程？",
          type: "select",
          required: true,
          options: [
            { label: "入门公开课", value: "intro_class" },
            { label: "主题工作坊", value: "workshop" },
            { label: "系统训练营", value: "bootcamp" },
            { label: "一对一辅导", value: "private_coaching" },
          ],
        },
        {
          key: "experience_level",
          label: "你的当前基础如何？",
          type: "radio",
          required: false,
          options: [
            { label: "零基础", value: "beginner" },
            { label: "有一点基础", value: "intermediate" },
            { label: "已有项目经验", value: "advanced" },
          ],
        },
        {
          key: "learning_goal",
          label: "你最想通过课程获得什么？",
          type: "textarea",
          required: true,
          placeholder: "请写下你的学习目标",
        },
      ],
    },
  },
  {
    id: "community-application",
    name: "社群入群申请",
    source: "public_benchmark",
    category: "社群运营",
    scenario: "私域社群、会员社区、行业交流群入群审核",
    description: "适合社群筛选、成员画像收集和入群通知。",
    theme: "dark",
    webhookPreset: "feishu_bot",
    suggestedPrompts: [
      "改成适合高质量创业者社群申请。",
      "增加可贡献资源字段，并让问题更有筛选力。",
    ],
    agentQuickActions: [
      "改成创业者社群",
      "增加可贡献资源字段",
      "让筛选问题更清晰",
      "生成入群审核提示",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "applicant_name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入姓名或昵称",
        },
        {
          key: "industry_city",
          label: "你的行业和所在城市是？",
          type: "text",
          required: false,
          placeholder: "例如：AI 产品，北京",
        },
        {
          key: "join_reason",
          label: "你为什么想加入这个社群？",
          type: "textarea",
          required: true,
          placeholder: "请简单说明你的期待",
        },
        {
          key: "contribution",
          label: "你可以为社群带来什么？",
          type: "textarea",
          required: false,
          placeholder: "例如经验、资源、案例、活动支持",
        },
        {
          key: "agree_rules",
          label: "是否愿意遵守社群规则？",
          type: "radio",
          required: true,
          options: [
            { label: "愿意", value: "yes" },
            { label: "需要先了解规则", value: "need_rules" },
          ],
        },
      ],
    },
  },
  {
    id: "beta-feedback",
    name: "Beta 产品反馈",
    source: "public_benchmark",
    category: "产品反馈",
    scenario: "内测产品、功能发布后收集使用反馈",
    description: "适合记录用户体验、问题复现和后续回访意愿。",
    theme: "dark",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合移动 App 内测反馈。",
      "增加问题严重程度，并让描述更便于产品团队跟进。",
    ],
    agentQuickActions: [
      "改成 App 内测反馈",
      "增加严重程度",
      "增加复现步骤",
      "生成产品复盘维度",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "product_version",
          label: "你体验的是哪个版本？",
          type: "text",
          required: true,
          placeholder: "例如：Web beta 0.3",
        },
        {
          key: "completed_actions",
          label: "你完成了哪些操作？",
          type: "checkbox",
          required: false,
          options: [
            { label: "注册登录", value: "signup" },
            { label: "创建内容", value: "create" },
            { label: "分享发布", value: "share" },
            { label: "提交数据", value: "submit" },
          ],
        },
        {
          key: "issue_description",
          label: "遇到了什么问题或不顺畅的地方？",
          type: "textarea",
          required: true,
          placeholder: "请描述具体场景，越具体越好",
        },
        {
          key: "experience_score",
          label: "整体体验如何？",
          type: "radio",
          required: true,
          options: [
            { label: "很好", value: "excellent" },
            { label: "还不错", value: "good" },
            { label: "一般", value: "average" },
            { label: "不太好", value: "poor" },
          ],
        },
        {
          key: "follow_up",
          label: "是否愿意接受后续回访？",
          type: "radio",
          required: false,
          options: [
            { label: "愿意", value: "yes" },
            { label: "暂不需要", value: "no" },
          ],
        },
      ],
    },
  },
  {
    id: "nps-survey",
    name: "NPS 推荐度调查",
    source: "public_benchmark",
    category: "客户体验",
    scenario: "产品、服务、课程交付后的推荐意愿调查",
    description: "适合快速衡量推荐意愿，并收集背后的关键原因。",
    theme: "minimal",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合 SaaS 产品 NPS 调查。",
      "增加差评原因分类，并生成客户成功跟进建议。",
    ],
    agentQuickActions: [
      "改成 SaaS NPS",
      "增加差评原因分类",
      "压缩成 3 个问题",
      "生成客户成功跟进建议",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "nps_score",
          label: "你愿意把我们推荐给朋友或同事吗？",
          type: "radio",
          required: true,
          options: [
            { label: "0-6 分，不太愿意", value: "detractor" },
            { label: "7-8 分，可以考虑", value: "passive" },
            { label: "9-10 分，非常愿意", value: "promoter" },
          ],
        },
        {
          key: "score_reason",
          label: "为什么给出这个分数？",
          type: "textarea",
          required: true,
          placeholder: "请写下最主要的原因",
        },
        {
          key: "best_part",
          label: "哪一点最值得保留？",
          type: "textarea",
          required: false,
          placeholder: "例如：功能、服务、交付速度",
        },
        {
          key: "improvement_area",
          label: "哪一点最需要改进？",
          type: "textarea",
          required: false,
          placeholder: "请写下你最希望我们优化的地方",
        },
        {
          key: "allow_follow_up",
          label: "是否允许我们进一步联系你？",
          type: "radio",
          required: false,
          options: [
            { label: "可以", value: "yes" },
            { label: "暂不需要", value: "no" },
          ],
        },
      ],
    },
  },
  {
    id: "user-interview-recruitment",
    name: "用户访谈招募",
    source: "public_benchmark",
    category: "用户研究",
    scenario: "产品调研、用户访谈、需求验证前招募受访者",
    description: "适合筛选目标用户、收集研究背景和可约时间。",
    theme: "minimal",
    webhookPreset: "feishu_bot",
    suggestedPrompts: [
      "改成适合 B 端 SaaS 用户访谈招募。",
      "增加使用频率字段，并让筛选问题更精准。",
    ],
    agentQuickActions: [
      "改成 B 端访谈招募",
      "增加使用频率字段",
      "强化筛选条件",
      "生成访谈邀约文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入姓名或昵称",
        },
        {
          key: "contact",
          label: "如何联系你？",
          type: "text",
          required: true,
          placeholder: "邮箱、手机号或微信",
        },
        {
          key: "user_segment",
          label: "你更接近哪类用户？",
          type: "select",
          required: true,
          options: [
            { label: "内容创作者", value: "creator" },
            { label: "创业团队", value: "startup" },
            { label: "企业员工", value: "enterprise_user" },
            { label: "学生 / 研究者", value: "student_researcher" },
            { label: "其他", value: "other" },
          ],
        },
        {
          key: "current_problem",
          label: "你现在最想解决的问题是什么？",
          type: "textarea",
          required: true,
          placeholder: "请描述当前工作流或使用场景",
        },
        {
          key: "available_time",
          label: "近期哪些时间方便访谈？",
          type: "text",
          required: false,
          placeholder: "例如：工作日晚上、周末下午",
        },
      ],
    },
  },
  {
    id: "content-download",
    name: "资料领取表",
    source: "public_benchmark",
    category: "内容转化",
    scenario: "白皮书、报告、案例集、清单工具下载前留资",
    description: "适合内容获客、资料分发和销售线索分层。",
    theme: "business",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合行业白皮书领取。",
      "增加公司规模字段，并生成资料发送提示文案。",
    ],
    agentQuickActions: [
      "改成白皮书领取",
      "增加公司规模字段",
      "压缩为高转化版本",
      "生成资料发送提示",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入姓名",
        },
        {
          key: "email",
          label: "资料发送到哪个邮箱？",
          type: "email",
          required: true,
          placeholder: "请输入邮箱",
        },
        {
          key: "company",
          label: "你所在公司或组织是？",
          type: "text",
          required: false,
          placeholder: "可选",
        },
        {
          key: "resource_type",
          label: "你想领取哪类资料？",
          type: "select",
          required: true,
          options: [
            { label: "白皮书", value: "whitepaper" },
            { label: "行业报告", value: "report" },
            { label: "案例集", value: "casebook" },
            { label: "实用清单", value: "checklist" },
          ],
        },
        {
          key: "contact_sales",
          label: "是否希望顾问进一步联系你？",
          type: "radio",
          required: false,
          options: [
            { label: "可以联系", value: "yes" },
            { label: "暂不需要", value: "no" },
          ],
        },
      ],
    },
  },
  {
    id: "customer-story",
    name: "客户案例征集",
    source: "public_benchmark",
    category: "品牌增长",
    scenario: "收集客户故事、用户反馈和可公开案例素材",
    description: "适合沉淀客户成功故事、案例线索和授权状态。",
    theme: "business",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合 SaaS 客户案例征集。",
      "增加公开授权选项，并让问题更适合写案例。",
    ],
    agentQuickActions: [
      "改成 SaaS 客户案例",
      "增加公开授权选项",
      "优化成故事结构",
      "生成案例采访提纲",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入姓名",
        },
        {
          key: "product_used",
          label: "你使用的是哪项产品或服务？",
          type: "text",
          required: true,
          placeholder: "请输入产品、服务或方案名称",
        },
        {
          key: "before_problem",
          label: "使用前遇到的主要问题是什么？",
          type: "textarea",
          required: true,
          placeholder: "请描述当时的背景和痛点",
        },
        {
          key: "after_result",
          label: "使用后带来了哪些变化或结果？",
          type: "textarea",
          required: true,
          placeholder: "可以写效率、收入、满意度或流程变化",
        },
        {
          key: "public_permission",
          label: "是否允许我们用于公开案例？",
          type: "radio",
          required: true,
          options: [
            { label: "可以实名公开", value: "public_named" },
            { label: "可以匿名公开", value: "public_anonymous" },
            { label: "暂不公开", value: "private_only" },
          ],
        },
        {
          key: "logo_file",
          label: "如方便，可上传品牌或项目图片。",
          type: "image",
          required: false,
          help_text: "可选，用于后续案例排版确认。",
        },
      ],
    },
  },
  {
    id: "portfolio-submission",
    name: "作品提交表",
    source: "public_benchmark",
    category: "作品征集",
    scenario: "作品集、项目案例、活动投稿和创作者征集",
    description: "适合收集作品链接、附件、创作说明和审核线索。",
    theme: "brutalism",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合设计作品征集。",
      "增加项目类型选项，并让审核信息更完整。",
    ],
    agentQuickActions: [
      "改成设计作品征集",
      "增加项目类型",
      "增加审核说明",
      "生成入选通知文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "creator_name",
          label: "怎么称呼你？",
          type: "text",
          required: true,
          placeholder: "请输入姓名或昵称",
        },
        {
          key: "project_name",
          label: "作品或项目名称是什么？",
          type: "text",
          required: true,
          placeholder: "请输入作品名称",
        },
        {
          key: "work_link",
          label: "作品链接是？",
          type: "text",
          required: false,
          placeholder: "例如网站、作品集、网盘链接",
        },
        {
          key: "work_file",
          label: "如有附件，可以上传作品文件。",
          type: "file",
          required: false,
          help_text: "支持上传图片、PDF 或其他作品文件。",
        },
        {
          key: "responsibility",
          label: "你在项目中负责什么？",
          type: "textarea",
          required: true,
          placeholder: "请描述你的角色、贡献和亮点",
        },
        {
          key: "notes",
          label: "还有什么补充说明？",
          type: "textarea",
          required: false,
          placeholder: "例如创作背景、获奖情况、合作需求",
        },
      ],
    },
  },
  {
    id: "invoice-receipt-collection",
    name: "发票票据收集表",
    source: "public_benchmark",
    category: "文件收集",
    scenario: "报销、费用归集、票据影像和基础信息收集",
    description: "适合收集票据图片、报销说明，并为 OCR 识别预留字段。",
    theme: "business",
    ocrTemplate: "invoice",
    webhookPreset: "dingtalk_bot",
    suggestedPrompts: [
      "改成适合差旅报销票据收集。",
      "增加费用类别，并让提交成功后推送到钉钉。",
    ],
    agentQuickActions: [
      "改成差旅报销",
      "增加费用类别",
      "检查 OCR 字段",
      "生成财务审核提示",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "applicant_name",
          label: "报销人姓名是？",
          type: "text",
          required: true,
          placeholder: "请输入姓名",
        },
        {
          key: "contact",
          label: "联系方式是？",
          type: "text",
          required: true,
          placeholder: "手机号、邮箱或企业 IM",
        },
        {
          key: "invoice_image",
          label: "请上传发票或票据图片。",
          type: "image",
          required: true,
          help_text: "图片越清晰，后续 OCR 识别效果越好。",
        },
        {
          key: "amount",
          label: "金额大概是多少？",
          type: "number",
          required: false,
          placeholder: "如已知可填写",
        },
        {
          key: "cost_category",
          label: "费用类别是？",
          type: "select",
          required: false,
          options: [
            { label: "差旅交通", value: "travel" },
            { label: "餐饮招待", value: "meal" },
            { label: "软件服务", value: "software" },
            { label: "其他费用", value: "other" },
          ],
        },
        {
          key: "remark",
          label: "补充说明",
          type: "textarea",
          required: false,
          placeholder: "例如项目名称、费用用途或审批备注",
        },
      ],
    },
  },
  {
    id: "identity-qualification-collection",
    name: "身份资质收集表",
    source: "public_benchmark",
    category: "资料审核",
    scenario: "身份材料、资质证明、准入审核资料收集",
    description: "适合收集基础信息、资质图片和授权确认。",
    theme: "business",
    ocrTemplate: "id_card",
    webhookPreset: "generic",
    suggestedPrompts: [
      "改成适合活动准入资质审核。",
      "增加授权确认，并让字段更适合人工复核。",
    ],
    agentQuickActions: [
      "改成活动准入审核",
      "增加授权确认",
      "检查隐私提示",
      "生成审核通过文案",
    ],
    formSchema: {
      layout: "single",
      fields: [
        {
          key: "applicant_name",
          label: "申请人姓名是？",
          type: "text",
          required: true,
          placeholder: "请输入真实姓名",
        },
        {
          key: "contact",
          label: "联系方式是？",
          type: "text",
          required: true,
          placeholder: "手机号或邮箱",
        },
        {
          key: "qualification_image",
          label: "请上传身份或资质证明图片。",
          type: "image",
          required: true,
          help_text: "请确保图片清晰，敏感信息按业务要求处理。",
        },
        {
          key: "application_purpose",
          label: "本次申请用途是？",
          type: "select",
          required: true,
          options: [
            { label: "会员认证", value: "membership" },
            { label: "活动准入", value: "event_access" },
            { label: "身份核验", value: "verification" },
            { label: "其他用途", value: "other" },
          ],
        },
        {
          key: "consent",
          label: "是否确认已获得提交和处理授权？",
          type: "radio",
          required: true,
          options: [
            { label: "确认", value: "yes" },
            { label: "暂不确认", value: "no" },
          ],
        },
        {
          key: "reviewer_note",
          label: "补充说明",
          type: "textarea",
          required: false,
          placeholder: "如有特殊情况，可在这里说明",
        },
      ],
    },
  },
];

export const homepageTemplateIds = [
  "lead-capture",
  "event-registration",
  "satisfaction-survey",
  "product-recommendation",
  "booking-consultation",
  "invoice-receipt-collection",
  "beta-feedback",
  "waitlist",
] as const;

export function getSceneTemplateById(templateId: string) {
  return sceneTemplates.find((template) => template.id === templateId);
}

export function getHomepageSceneTemplates() {
  return homepageTemplateIds
    .map((templateId) => getSceneTemplateById(templateId))
    .filter((template): template is SceneTemplate => Boolean(template));
}

export function buildGeneratedFormDraftFromTemplate(template: SceneTemplate): GeneratedFormDraft {
  return {
    title: template.name,
    description: template.description,
    theme: template.theme,
    schema: JSON.parse(JSON.stringify(template.formSchema)),
    source: "template",
    model: template.id,
    ocr_template: template.ocrTemplate,
  };
}
