"use client";

import { ReactNode } from "react";
import {
  RiAddCircleLine,
  RiAddLine,
  RiAlertLine,
  RiArchiveLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowRightUpLine,
  RiArrowUpLine,
  RiArticleLine,
  RiBankCardLine,
  RiBarChart2Line,
  RiBarChartBoxLine,
  RiBookLine,
  RiClapperboardAiLine,
  RiCloudy2Fill,
  RiCodeFill,
  RiFileCopy2Line, // Replacement for RiCopy2Line
  RiCustomerService2Line,
  RiDatabase2Line,
  RiDiscordFill,
  RiDiscordLine,
  RiDownloadLine,
  RiEditLine,
  RiEmotionSadFill,
  RiErrorWarningLine,
  RiEyeLine,
  RiFileList3Line,
  RiFilePaperLine,
  RiFileWarningLine,
  RiFlashlightFill,
  RiFilter2Line, // Replacement for RiFunnelLine
  RiGithubFill,
  RiGithubLine,
  RiHome5Line,
  RiHomeLine,
  RiImageLine,
  RiInboxLine,
  RiKey2Fill,
  RiKey2Line,
  RiLayoutGridLine,
  RiLineChartLine,
  RiLink,
  RiMagicLine,
  RiMailLine,
  RiNextjsFill,
  RiNodeTree,
  RiOrderPlayLine,
  RiPieChart2Line,
  RiPlug2Line,
  RiPrinterLine,
  RiPulseLine,
  RiRefreshLine,
  RiRobot2Line,
  RiRocket2Line,
  RiSave3Line,
  RiSaveLine,
  RiSearch2Line,
  RiSearchEyeLine,
  RiSearchLine,
  RiSendPlaneFill,
  RiSettings3Line,
  RiShieldCheckLine,
  RiSparklingLine,
  RiTeamLine,
  RiTimeLine,
  RiTwitterLine,
  RiUserLine,
  RiUserSmileLine,
  RiVipDiamondLine,
} from "react-icons/ri";

const iconMap: { [key: string]: React.ComponentType<any> } = {
  RiAddCircleLine,
  RiAddLine,
  RiAlertLine,
  RiArchiveLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowRightUpLine,
  RiArrowUpLine,
  RiArticleLine,
  RiBankCardLine,
  RiBarChart2Line,
  RiBarChartBoxLine,
  RiBookLine,
  RiClapperboardAiLine,
  RiCloudy2Fill,
  RiCodeFill,
  RiCopy2Line: RiFileCopy2Line, // Map string key used in config to the actual icon
  RiCustomerService2Line,
  RiDatabase2Line,
  RiDiscordFill,
  RiDiscordLine,
  RiDownloadLine,
  RiEditLine,
  RiEmotionSadFill,
  RiErrorWarningLine,
  RiEyeLine,
  RiFileList3Line,
  RiFilePaperLine,
  RiFileWarningLine,
  RiFlashlightFill,
  RiFunnelLine: RiFilter2Line, // Map string key used in config to the actual icon
  RiGithubFill,
  RiGithubLine,
  RiHome5Line,
  RiHomeLine,
  RiImageLine,
  RiInboxLine,
  RiKey2Fill,
  RiKey2Line,
  RiLayoutGridLine,
  RiLineChartLine,
  RiLink,
  RiMagicLine,
  RiMailLine,
  RiNextjsFill,
  RiNodeTree,
  RiOrderPlayLine,
  RiPieChart2Line,
  RiPlug2Line,
  RiPrinterLine,
  RiPulseLine,
  RiRefreshLine,
  RiRobot2Line,
  RiRocket2Line,
  RiSave3Line,
  RiSaveLine,
  RiSearch2Line,
  RiSearchEyeLine,
  RiSearchLine,
  RiSendPlaneFill,
  RiSettings3Line,
  RiShieldCheckLine,
  RiSparklingLine,
  RiTeamLine,
  RiTimeLine,
  RiTwitterLine,
  RiUserLine,
  RiUserSmileLine,
  RiVipDiamondLine,
};

export default function Icon({
  name,
  className,
  onClick,
}: {
  name: string;
  className?: string;
  onClick?: () => void;
}) {
  const IconComponent = iconMap[name];

  if (!IconComponent) return null;

  return (
    <IconComponent
      className={className}
      onClick={onClick}
      style={{ cursor: onClick ? "pointer" : "default" }}
    />
  );
}
