import SkillsCatalogClient from "@/components/skills/skills-catalog-client";
import { notFound } from "next/navigation";

interface Props {
  params: Promise<{ locale: string; skillId: string }>;
}



export async function generateMetadata({ params }: Props) {
  const { locale, skillId } = await params;
  const isZh = (locale || "zh").toLowerCase().startsWith("zh");
  const baseUrl = process.env.NEXT_PUBLIC_WEB_URL || "https://aifactory.ai";
  const canonicalUrl =
    locale === "en"
      ? `${baseUrl}/skills-catalog/${skillId}`
      : `${baseUrl}/${locale}/skills-catalog/${skillId}`;

  // Custom SEO details per skill
  const skillMetaMap: Record<string, { title: string; desc: string; keywords: string }> = {
    deduplication: {
      title: isZh 
        ? "数据查重与附件去重拦截技能 - AI FormFactory" 
        : "Automated Deduplication & Fraud Interception Guard - AI FormFactory",
      desc: isZh 
        ? "自动对比上传表单附件的哈希值（SHA256/MD5），并在已填报历史数据中比对手机号、邮箱、发票号等唯一业务字段，智能拦截重复录入与发票重复报销。" 
        : "Compute file hashes and verify business keys against historical submissions to intercept duplicates and fraudulent invoice entries automatically.",
      keywords: isZh 
        ? "发票查重, 数据去重, 附件哈希比对, 重复报销拦截, 表单去重" 
        : "invoice deduplication, duplicate blocker, file hash audit, fraud detection, form validation",
    },
    table_ocr: {
      title: isZh 
        ? "多行表格图片 OCR 智能解析与字段回填技能 - AI FormFactory" 
        : "Image Table OCR Parsing & Multi-row Field Pre-fills - AI FormFactory",
      desc: isZh 
        ? "基于高精度视觉 OCR 与 LLM 语义识别，自动从设备采购清单、财务明细发票图片中切割解析网格数据，智能对齐表头并批量回填到子表格表单中。" 
        : "Leverage premium cloud OCR and LLM reasoning to segment and extract multi-row spreadsheets from receipt images and auto fill complex form sub-tables.",
      keywords: isZh 
        ? "表格OCR, 明细识别, 图片转表格, 数据回填, 采购表格解析" 
        : "table OCR, receipts scanner, image grid extraction, sub-table fill, spreadsheet parser",
    },
    ai_pre_audit: {
      title: isZh 
        ? "AI 规则合规预审与报销额度自动初审技能 - AI FormFactory" 
        : "AI Pre-audit Compliance & Budget Validation - AI FormFactory",
      desc: isZh 
        ? "支持企业导入自定义自然语言政策文件。大模型会在用户提交表单（如出差报销、活动审批）后，根据限额和合规提示词进行语义初审，自动预警超标漏洞。" 
        : "Deploy custom policy prompts to automatically audit submissions. Detect expense limits violations and flag suspicious business justifications in real-time.",
      keywords: isZh 
        ? "AI合规审查, 报销额度初审, 大模型智审, 异常警示, 企业规则核算" 
        : "AI compliance check, policy enforcement, expense pre-audit, budget checker, exception audit",
    },
    report_export: {
      title: isZh 
        ? "数据报表自动导出与 AI 趋势诊断分析技能 - AI FormFactory" 
        : "Smart PDF/Excel Report Export & AI Analytics - AI FormFactory",
      desc: isZh 
        ? "支持将收集到的表单明细数据一键打包导出为 Excel、CSV 或高颜值 PDF 报表。导出前由大模型读取趋势并自动撰写专业的月度/季度智能摘要。" 
        : "Export form databases to custom styled Excel or PDF templates with automated trend analysis and dashboard diagnostics generated by LLMs.",
      keywords: isZh 
        ? "报表导出, Excel自动汇总, PDF报表渲染, AI数据摘要, 数据分析报表" 
        : "report generator, excel export, PDF styling, AI trend summary, business report automation",
    },
    email_notification: {
      title: isZh 
        ? "邮件通知与联动附件发送技能 - AI FormFactory" 
        : "Automated Email Notifications & Report Attachments Chaining - AI FormFactory",
      desc: isZh 
        ? "支持在新提交时向表单创建者、指定邮箱或通过表单收集的填报人邮箱发送邮件通知，支持在邮件正文中动态插入填报变量，并支持与智能报表导出技能联合，自动打包并附带生成的 Excel/PDF 报表作为附件发送。" 
        : "Automatically trigger emails on form submission to creators, custom addresses, or responders. Customize subjects and bodies with dynamic placeholders. Chain with smart reports to automatically attach compiled Excel/PDF files.",
      keywords: isZh 
        ? "邮件通知, 填报回执, 邮件自动发送, 报表附件发送, 流程通知" 
        : "email notification, auto responder, receipt automation, report attachment mailer, mail workflow",
    },
    data_cleaning: {
      title: isZh 
        ? "AI 数据自动清洗与格式规范化技能 - AI FormFactory" 
        : "AI Automated Data Cleaning & Input Normalization - AI FormFactory",
      desc: isZh 
        ? "支持在大数据收集后自动清洗常见脏数据。一键去除首尾空格、一键邮箱拼写规范化、自动清除手机号无效横杠与空格，保障入库数据格式规整，大幅降低后续统计与流转的人工成本。" 
        : "Clean and normalize form payloads automatically. Trim whitespaces, lowercase email inputs, and sanitize phone numbers to prevent database pollution and manual re-formatting.",
      keywords: isZh 
        ? "数据清洗, 手机号格式化, 邮箱转小写, 空格清理, 脏数据过滤" 
        : "data cleaning, phone format, lowercase email, trim whitespace, dirty data check",
    },
    ai_insights: {
      title: isZh 
        ? "AI 数据智能摘要与业务趋势洞察技能 - AI FormFactory" 
        : "AI Submission Summaries & Business Insights - AI FormFactory",
      desc: isZh 
        ? "利用大语言模型在提交后提供深度语义诊断。支持配置特定的金额高值警报线、摘要风格（商业、销售线索、风险巡检）、高额阈值提示，并自动提炼出高价值建议与下一步行动指南。" 
        : "Leverage Large Language Models to generate deep business contexts. Configure custom summary styles, high-value alerts thresholds, and auto generate diagnostic recommendations on the fly.",
      keywords: isZh 
        ? "AI摘要, 数据分析洞察, 大模型初审, 高值告警, 行动建议生成" 
        : "AI summary, business insights, LLM trends, high-value triggers, next actions generator",
    },
  };

  const meta = skillMetaMap[skillId] || {
    title: isZh ? "AI 智能集成技能 - AI FormFactory" : "AI Smart Integration Skill - AI FormFactory",
    desc: isZh ? "探索强大的 AI Form 自动化与智能集成技能。" : "Explore advanced AI form automation integrations.",
    keywords: "AI Form, Skills Center",
  };

  return {
    title: meta.title,
    description: meta.desc,
    keywords: meta.keywords,
    alternates: {
      canonical: canonicalUrl,
      languages: {
        en: `${baseUrl}/skills-catalog/${skillId}`,
        zh: `${baseUrl}/zh/skills-catalog/${skillId}`,
      },
    },
    openGraph: {
      title: meta.title,
      description: meta.desc,
      url: canonicalUrl,
      siteName: "AI FormFactory",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.desc,
    },
  };
}

export default async function SkillDetailPage({ params }: Props) {
  const { locale, skillId } = await params;
  
  const allowedSkills = ["deduplication", "table_ocr", "ai_pre_audit", "report_export", "email_notification", "data_cleaning", "ai_insights"];
  if (!allowedSkills.includes(skillId)) {
    notFound();
  }

  return <SkillsCatalogClient locale={locale} skillId={skillId} />;
}
